apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-gitops
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jay-2000/Mern-stack-via-EKS.git
    targetRevision: main
    path: helm/mern-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
