apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jay-2000/Mern-stack-via-EKS'
    targetRevision: main
    path: infra/helm-charts/charts
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mern
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
